version: 0.2

phases:
  install:
    commands:
      - echo install packages here.
  pre_build:
    commands:
      - echo pre build maybe install dependencies here...
  build:
    commands:
      - echo Build started on `date`
      - echo might use this to run mocha
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
   files:
     - '**/*'
